### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by izaim** [mkhost/whmcs#1]

**Comment by mkhost** [comment]
Hi,

Code is maintained. It is not tested on WHMCS 8. It works on PHP 7.4.

We will test it on WHMCS 8 very soon. Feel free to use it and if there are some issues contact us.

**Comment by mkhost** [comment]
https://mkhost.com/mk/

reply@reply.github.com


Број на корисник: #



 


 

 Твојот тикет за поддршка е отворен




Здраво mkhost/whmcs, ти благодариме што го исконтактира нашиот тим за поддршка!




Ова е потврда дека твоето барање за отворање на тикет за поддршка е успешно. Ќе бидеш известен по емаил кога нашиот тим за поддршка ќе одговори на тикетот.





Број на тикет: 470997




Наслов: #Re: [mkhost/whmcs] Compatibility (#1)




Приоритет: Среден




Статус: Отворено





https://portal.mkhost.com/login за да го погледнеш тикетот, или за да одговориш на истиот.



https://portal.mkhost.com/help-desk/ticket/97110

Доколку имаш дополнителни прашања, слободно контактирај нѐ во било кое време.




Тимот на МКхост






Имаш прашања? Јави се на https://mkhost.com/mk/other/contact


Можеш да отвориш и тикет за поддршка.



https://portal.mkhost.com/help-desk/open-ticket
 



https://mkhost.com/mk/ https://portal.mkhost.com/login
 






Овој автоматски емаил го добиваш бидејќи си регистриран корисник на МКхост. За да управуваш со твоите емаил преференци https://portal.mkhost.com/login.




Ја почитуваме твојата приватност. Погледни ја нашата https://mkhost.com/mk/other/legal.



 

© МКхост ДООЕЛ. Сите права се задржани.
Јане Сандански 71А А.4.7 1000 Скопје, МК




https://www.facebook.com/mkhost/
https://www.linkedin.com/company/mkhost/
https://www.youtube.com/channel/UCeaZIGgr2pxgRDqefYH4reQ
https://blog.mkhost.com.mk/
